### ISSUE TITLE
Cosmetic issue with control creation message

### ISSUE THREAD

**Issue by javierdeposada-agilecontent** [intuitem/ciso-assistant-community#771] opened 2024-08-29 06:23 UTC
**Describe the bug**
Cosmetic issue with a message

**To Reproduce**
Under Risk Scenario, add new applied control and save

**Expected behavior**
Just a more customized message, or a generic "control creation OK"

**Screenshots**
![image](https://github.com/user-attachments/assets/f8c6ab76-c6a3-4e75-8f42-2bc1a0b34242)

**Environment (please complete the following information):**
 Edge MacOS

**Additional context**

**Comment by nas-tabchiche** [comment] 2024-08-29 12:48
Hi @javierdeposada-agilecontent,
The issue is fixed with #772. It will be live once the branch is merged.
Thank you for the input.

**Closed by nas-tabchiche** 2024-08-29 12:48 UTC
