### ISSUE TITLE
Library/compliance : Impossible to re-upload / framework after deletion.

### ISSUE THREAD

**Issue by whoo** [intuitem/ciso-assistant-community#664] opened 2024-07-17 12:24 UTC
**Describe the bug**
In the Compliance > Frameworks section, if a framework is deleted, it cannot be imported again.

**To Reproduce**
1. Go to 'Compliance > Frameworks'
2. Click on 'Import Framework'
3. Import NIST-CSF( as exemple) | The library should be successfully uploaded
4. Go to 'Compliance > Frameworks'
5. Delete NIST-CST | The library should be successfully unload
6. Go to 'Compliance > Frameworks'
7. Click on 'Import Framework'
8. you cannot import NIST-CSF anymore.

**Expected behavior**
Framwork could be loaded do Compliance>Frameworks.

**Environment (please complete the following information):**
 - Docker environnement.
 

Tks.

**Comment by ab-smith** [comment] 2024-07-17 12:52
thank you @whoo for the feedback. This is a regression indeed due to the caching system and will be fixed.
In the meanwhile, if you take away the framework from the `Loaded libraries` it shall do the trick for you:
<img width="435" alt="image" src="https://github.com/user-attachments/assets/3c50cab2-63d7-4fa0-898b-1b140e781855">

**Comment by ab-smith** [comment] 2024-07-27 07:09
fixed in v1.6.3

**Closed by ab-smith** 2024-07-27 07:09 UTC
Labels: bug
